import { useState } from 'react';
import { Sparkles, User, Cpu, Smartphone, Plus, ChevronLeft, ChevronRight } from 'lucide-react';
import { Resource } from './ResourceCard';

interface CompatibleSet {
  id: string;
  employee: Resource;
  machine: Resource;
  device: Resource;
  upfrontCost: number;
  monthlyCost: number;
}

interface AutoGeneratedSetsViewProps {
  allResources: Resource[];
  onSelectResource: (id: string) => void;
}

export function AutoGeneratedSetsView({ allResources, onSelectResource }: AutoGeneratedSetsViewProps) {
  const [currentPage, setCurrentPage] = useState(1);
  const ITEMS_PER_PAGE = 15;

  const generateCompatibleSets = (): CompatibleSet[] => {
    const sets: CompatibleSet[] = [];
    let setId = 1;

    // Get all employees
    const employees = allResources.filter(r => r.type === 'employees');

    employees.forEach(employee => {
      // Get machines this employee can operate
      const compatibleMachines = (employee.compatibleMachineIds || [])
        .map(id => allResources.find(r => r.id === id))
        .filter(Boolean) as Resource[];

      compatibleMachines.forEach(machine => {
        // Find devices compatible with both the employee and the machine
        const sharedDeviceIds = employee.compatibleDeviceIds?.filter(
          deviceId => machine.compatibleDeviceIds?.includes(deviceId)
        ) || [];

        const sharedDevices = sharedDeviceIds
          .map(id => allResources.find(r => r.id === id))
          .filter(Boolean) as Resource[];

        // Create a set for each compatible device
        sharedDevices.forEach(device => {
          const upfrontCost = employee.initialCost + machine.initialCost + device.initialCost;
          const monthlyCost = employee.monthlyCost + machine.monthlyCost + device.monthlyCost;

          sets.push({
            id: `auto-${setId++}`,
            employee,
            machine,
            device,
            upfrontCost,
            monthlyCost
          });
        });
      });
    });

    return sets;
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 0 }).format(amount);
  };

  const compatibleSets = generateCompatibleSets();
  const totalPages = Math.ceil(compatibleSets.length / ITEMS_PER_PAGE);
  const startIndex = (currentPage - 1) * ITEMS_PER_PAGE;
  const endIndex = startIndex + ITEMS_PER_PAGE;
  const currentSets = compatibleSets.slice(startIndex, endIndex);

  const handleAddSet = (set: CompatibleSet) => {
    onSelectResource(set.employee.id);
    onSelectResource(set.machine.id);
    onSelectResource(set.device.id);
  };

  return (
    <div className="space-y-4">
      {/* Info Banner */}
      <div className="bg-[var(--mint-subtle)] border border-[var(--mint)]/30 rounded-xl p-4 flex items-start gap-3">
        <Sparkles className="w-5 h-5 text-[var(--mint-dark)] flex-shrink-0 mt-0.5" />
        <div>
          <h3 className="text-sm text-[var(--navy)] font-medium mb-1">System-Generated Compatible Sets</h3>
          <p className="text-xs text-muted-foreground">
            These are automatically generated resource sets where the employee can operate both the machine and the device, 
            and the device is compatible with the machine. All compatibility constraints are satisfied.
          </p>
        </div>
      </div>

      {/* Table */}
      <div className="bg-white rounded-xl border border-border overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-muted/50 border-b border-border">
              <tr>
                <th className="px-4 py-3 text-left text-xs text-muted-foreground font-medium">Employee</th>
                <th className="px-4 py-3 text-left text-xs text-muted-foreground font-medium">Machine</th>
                <th className="px-4 py-3 text-left text-xs text-muted-foreground font-medium">Device</th>
                <th className="px-4 py-3 text-right text-xs text-muted-foreground font-medium">Upfront Cost</th>
                <th className="px-4 py-3 text-right text-xs text-muted-foreground font-medium">Monthly Cost</th>
                <th className="px-4 py-3 text-right text-xs text-muted-foreground font-medium">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {currentSets.map((set) => (
                <tr key={set.id} className="hover:bg-muted/20 transition-colors">
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-2">
                      <div className="p-1.5 bg-[var(--employee-bg)] rounded">
                        <User className="w-3.5 h-3.5 text-[var(--employee-color)]" />
                      </div>
                      <div className="min-w-0">
                        <p className="text-sm text-[var(--navy)] truncate">{set.employee.name}</p>
                        <p className="text-xs text-muted-foreground truncate">{set.employee.department}</p>
                      </div>
                    </div>
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-2">
                      <div className="p-1.5 bg-[var(--machine-bg)] rounded">
                        <Cpu className="w-3.5 h-3.5 text-[var(--machine-color)]" />
                      </div>
                      <div className="min-w-0">
                        <p className="text-sm text-[var(--navy)] truncate">{set.machine.name}</p>
                        <p className="text-xs text-muted-foreground truncate">{set.machine.location}</p>
                      </div>
                    </div>
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-2">
                      <div className="p-1.5 bg-[var(--device-bg)] rounded">
                        <Smartphone className="w-3.5 h-3.5 text-[var(--device-color)]" />
                      </div>
                      <div className="min-w-0">
                        <p className="text-sm text-[var(--navy)] truncate">{set.device.name}</p>
                        <p className="text-xs text-muted-foreground truncate">{set.device.department}</p>
                      </div>
                    </div>
                  </td>
                  <td className="px-4 py-3 text-right">
                    <p className="text-sm text-[var(--navy)] font-semibold">{formatCurrency(set.upfrontCost)}</p>
                  </td>
                  <td className="px-4 py-3 text-right">
                    <p className="text-sm text-muted-foreground">{formatCurrency(set.monthlyCost)}</p>
                  </td>
                  <td className="px-4 py-3 text-right">
                    <button
                      onClick={() => handleAddSet(set)}
                      className="inline-flex items-center gap-1 px-3 py-1.5 bg-[var(--mint)] text-white rounded-lg hover:bg-[var(--mint-dark)] transition-colors text-xs"
                    >
                      <Plus className="w-3 h-3" />
                      Add Set
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        {totalPages > 1 && (
          <div className="px-4 py-3 border-t border-border flex items-center justify-between bg-muted/30">
            <div className="text-xs text-muted-foreground">
              Showing {startIndex + 1}–{Math.min(endIndex, compatibleSets.length)} of {compatibleSets.length} compatible sets
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                disabled={currentPage === 1}
                className="p-1.5 rounded-lg hover:bg-muted transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
              >
                <ChevronLeft className="w-4 h-4 text-[var(--navy)]" />
              </button>
              <div className="flex items-center gap-1">
                {Array.from({ length: Math.min(5, totalPages) }, (_, i) => {
                  let pageNum;
                  if (totalPages <= 5) {
                    pageNum = i + 1;
                  } else if (currentPage <= 3) {
                    pageNum = i + 1;
                  } else if (currentPage >= totalPages - 2) {
                    pageNum = totalPages - 4 + i;
                  } else {
                    pageNum = currentPage - 2 + i;
                  }

                  return (
                    <button
                      key={i}
                      onClick={() => setCurrentPage(pageNum)}
                      className={`px-2.5 py-1 rounded text-xs transition-colors ${
                        currentPage === pageNum
                          ? 'bg-[var(--navy)] text-white'
                          : 'hover:bg-muted text-[var(--navy)]'
                      }`}
                    >
                      {pageNum}
                    </button>
                  );
                })}
              </div>
              <button
                onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
                disabled={currentPage === totalPages}
                className="p-1.5 rounded-lg hover:bg-muted transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
              >
                <ChevronRight className="w-4 h-4 text-[var(--navy)]" />
              </button>
            </div>
          </div>
        )}
      </div>

      {compatibleSets.length === 0 && (
        <div className="text-center py-12">
          <Sparkles className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
          <p className="text-muted-foreground">No compatible sets found</p>
        </div>
      )}
    </div>
  );
}
