
import { useState, useMemo } from 'react';
import { Sparkles, Plus } from 'lucide-react';
import { ResourceSetTable, ResourceSet } from './ResourceSetTable';



interface AutoGeneratedSetsViewProps {
  allResources: import('../Type').Resource[];
  onSelectResource: (id: string) => void;
  onAddSet?: (set: ResourceSet) => void;
}

const generateCompatibleSets = (allResources: import('../Type').Resource[]): ResourceSet[] => {
  const sets: ResourceSet[] = [];
  let setId = 1;
  const employees = allResources.filter((r: any) => r.type === 'employees');
  employees.forEach((employee: any) => {
    const compatibleMachines = (employee.compatibleMachineIds || [])
      .map((id: any) => allResources.find((r: any) => r.id === id))
      .filter(Boolean) as any[];
    compatibleMachines.forEach((machine: any) => {
      const sharedDeviceIds = employee.compatibleDeviceIds?.filter(
        (deviceId: any) => machine.compatibleDeviceIds?.includes(deviceId)
      ) || [];
      const sharedDevices = sharedDeviceIds
        .map((id: any) => allResources.find((r: any) => r.id === id))
        .filter(Boolean) as any[];
      sharedDevices.forEach((device: any) => {
        sets.push({
          id: `auto-${setId++}`,
          name: `${employee.name} + ${machine.name} + ${device.name}`,
          resources: [employee, machine, device],
          createdAt: new Date(),
        });
      });
    });
  });
  return sets;
};

export function AutoGeneratedSetsView({ allResources, onSelectResource, onAddSet }: AutoGeneratedSetsViewProps) {
  const compatibleSets: ResourceSet[] = useMemo(() => generateCompatibleSets(allResources), [allResources]);

  const handleAddSet = (set: ResourceSet) => {
    if (onAddSet) {
      onAddSet(set);
    } else {
      set.resources.forEach(r => onSelectResource(r.id));
    }
  };

  return (
    <div className="space-y-4">
      {/* Info Banner */}
      <div className="bg-[var(--mint-subtle)] border border-[var(--mint)]/30 rounded-xl p-4 flex items-start gap-3">
        <Sparkles className="w-5 h-5 text-[var(--mint-dark)] flex-shrink-0 mt-0.5" />
        <div>
          <h3 className="text-sm text-[var(--navy)] font-medium mb-1">System-Generated Compatible Sets</h3>
          <p className="text-xs text-muted-foreground">
            These are automatically generated resource sets where the employee can operate both the machine and the device, 
            and the device is compatible with the machine. All compatibility constraints are satisfied.
          </p>
        </div>
      </div>
      <ResourceSetTable
        sets={compatibleSets}
        showActions={false}
        itemsPerPage={15}
        renderAction={(set: ResourceSet) => (
          <button
            onClick={() => handleAddSet(set)}
            className="inline-flex items-center gap-1 px-3 py-1.5 bg-[var(--mint)] text-white rounded-lg hover:bg-[var(--mint-dark)] transition-colors text-xs"
          >
            <Plus className="w-3 h-3" />
            Add Set
          </button>
        )}
      />
      {compatibleSets.length === 0 && (
        <div className="text-center py-12">
          <Sparkles className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
          <p className="text-muted-foreground">No compatible sets found</p>
        </div>
      )}
    </div>
  );
}
