import { test, expect } from '@playwright/test';

// This test assumes your app is running locally on http://localhost:5173 or similar
// Adjust the URL and selectors as needed for your actual app
test.setTimeout(60000);
test.describe('Advanced Filters - Emily Rodriguez', () => {
    test.beforeEach(async ({ page }) => {
      await page.goto('http://localhost:5173');
      await page.waitForLoadState('networkidle');
      await page.getByText('Saved Sets').click();
      while (await page.locator('button[title="Delete set"]').count() > 0) {
        await page.locator('button[title="Delete set"]').first().click();
        await page.waitForTimeout(200);
      }
      await page.getByText('Resources').click();
    });
  test('adds set from Autogenerated view and verifies it in Saved Resource Sets', async ({ page }) => {
    await page.goto('http://localhost:5173');
    await page.waitForLoadState('networkidle');
    await page.getByText('Compatible Sets').click();
    const firstRow = page.locator('tr').filter({ has: page.getByRole('button', { name: /AddSet|Add Set/i }) }).first();
    await expect(firstRow).toBeVisible();
    const employee = await firstRow.locator('[data-testid="employee-cell"]').innerText();
    const machine = await firstRow.locator('[data-testid="machine-cell"]').innerText();
    const device = await firstRow.locator('[data-testid="device-cell"]').innerText();
    const upfrontCost = await firstRow.locator('[data-testid="upfront-cost-cell"]').innerText();
    const monthlyCost = await firstRow.locator('[data-testid="monthly-cost-cell"]').innerText();
    await firstRow.getByRole('button', { name: /AddSet|Add Set/i }).click();
    await page.getByText('Saved Sets').click();
    await page.getByText('Saved Sets').click();
    await expect(page.getByRole('heading', { name: /Saved Resource Sets/i })).toBeVisible();
    const savedRow = page.locator('tr', { hasText: /Resource Set 1/ });
    await expect(savedRow).toBeVisible();
    const sEmployee = await savedRow.locator('[data-testid="employee-cell"]').innerText().catch(() => '');
    const sMachine = await savedRow.locator('[data-testid="machine-cell"]').innerText().catch(() => '');
    const sDevice = await savedRow.locator('[data-testid="device-cell"]').innerText().catch(() => '');
    const sUpfrontCost = await savedRow.locator('[data-testid="upfront-cost-cell"]').innerText().catch(() => '');
    const sMonthlyCost = await savedRow.locator('[data-testid="monthly-cost-cell"]').innerText().catch(() => '');
    expect(sEmployee, 'Employee matches').toContain(employee);
    expect(sMachine, 'Machine matches').toContain(machine);
    expect(sDevice, 'Device matches').toContain(device);
    expect(sUpfrontCost, 'Upfront cost matches').toContain(upfrontCost);
    expect(sMonthlyCost, 'Monthly cost matches').toContain(monthlyCost);
  });
  test('adds resources to a set and verifies it appears in saved sets', async ({ page }) => {
    await page.goto('http://localhost:5173');
    await page.waitForLoadState('networkidle');
    await page.getByText('All Resources').click();
    await page.getByPlaceholder('Search resources...').fill('Emily Rodriguez');

    await page.getByRole('button', { name: 'Add to Set' }).click();
    await page.getByPlaceholder('Search resources...').fill('Robot Arm V5');
    await expect(page.getByText('Robot Arm V5')).toBeVisible();
    await page.getByRole('button', { name: 'Add to Set' }).click();
    await page.getByPlaceholder('Search resources...').fill('MacBook Pro 16"');
    await expect(page.getByText('MacBook Pro 16"')).toBeVisible();
    await page.getByRole('button', { name: 'Add to Set' }).click();
    await page.getByPlaceholder('Search resources...').fill('');
    await page.getByRole('button', { name: 'Save Resource Set' }).click();
    await expect(page.getByRole('heading', { name: /Saved Resource Sets/i })).toBeVisible();
  const setRow = page.locator('tr', { hasText: /Resource Set 1/ });
  await expect(setRow).toBeVisible();
  await expect(setRow.locator('td', { hasText: /Emily Rodriguez/ })).toBeVisible();
  await expect(setRow.locator('td', { hasText: /Robot Arm V5/ })).toBeVisible();
  await expect(setRow.locator('td', { hasText: /MacBook Pro 16"/ })).toBeVisible();
  });
    test('toggles global filter logic AND/OR and updates label and results', async ({ page }) => {
      await page.goto('http://localhost:5173');
      await page.waitForLoadState('networkidle');
      await page.getByText('Employees').click();
      await page.getByText('Advanced Filters').click();
      // Dodaj dwa filtry
      await page.getByLabel('Machines').selectOption({ label: 'Robot Arm V5' });
      await page.getByLabel('Devices').selectOption({ label: 'Steam Deck' });
      // Sprawdź, że przycisk logiczny jest widoczny i ma tekst AND
      const logicButton = page.getByTestId('logic-toggle');
      await expect(logicButton).toHaveText('AND');
      // Kliknij przycisk logiczny (zmiana na OR)
      await logicButton.click();
      await expect(logicButton).toHaveText('OR');
      // Sprawdź, że Emily Rodriguez jest widoczna (OR logic)
      await expect(page.getByText('Emily Rodriguez')).toBeVisible();
      // Kliknij ponownie, zmiana na AND
      await logicButton.click();
      await expect(logicButton).toHaveText('AND');
      // Sprawdź, że Emily Rodriguez nie jest widoczna (AND logic)
      await expect(page.getByText('Emily Rodriguez')).not.toBeVisible();
    });
  test('shows Emily Rodriguez for Robot Arm V5 (Machine) filter', async ({ page }) => {
    await page.goto('http://localhost:5173');
    await page.waitForLoadState('networkidle');
    await page.getByText('Employees').click();
    await page.getByText('Advanced Filters').click();
    await page.getByLabel('Machines').selectOption({ label: 'Robot Arm V5' });
    await expect(page.getByText('Emily Rodriguez')).toBeVisible();
  });

  test('shows Emily Rodriguez for Robot Arm V5 OR Steam Deck filter', async ({ page }) => {
    await page.goto('http://localhost:5173');
    await page.getByText('Employees').click();
    await page.getByText('Advanced Filters').click();
    await page.getByLabel('Machines').selectOption({ label: 'Robot Arm V5' });
    await page.getByLabel('Devices').selectOption({ label: 'Steam Deck' });
    // Przełącz logikę na OR
    const logicButton = page.getByTestId('logic-toggle');
    await logicButton.click();
    await expect(page.getByText('Emily Rodriguez')).toBeVisible();
  });

  test('hides Emily Rodriguez for Robot Arm V5 AND Steam Deck filter', async ({ page }) => {
    await page.goto('http://localhost:5173');
    await page.getByText('Employees').click();
    await page.getByText('Advanced Filters').click();
    await page.getByLabel('Machines').selectOption({ label: 'Robot Arm V5' });
    await page.getByLabel('Devices').selectOption({ label: 'Steam Deck' });
    // Domyślnie jest AND, więc Emily nie powinna być widoczna
    await expect(page.getByText('Emily Rodriguez')).not.toBeVisible();
    // Kliknij przycisk logiczny, by zmienić na OR
    const logicButton = page.getByTestId('logic-toggle');
    await logicButton.click();
    // Teraz Emily powinna być widoczna (OR logic)
    await expect(page.getByText('Emily Rodriguez')).toBeVisible();
  });
  //   test('advanced filters: AND/OR logic with two machines and two employees', async ({ page }) => {
  //   await page.goto('http://localhost:5173');
  //   await page.waitForLoadState('networkidle');
  //   await page.getByText('Employees').click();
  //   await page.getByText('Advanced Filters').click();

  //   await page.getByLabel('Machines').selectOption({ label: 'Robot Arm V5' });
  //   await page.getByLabel('Machines').selectOption({ label: '3D Printer Pro' });

  //   const logicButton = page.getByTestId('logic-toggle');
  //   await expect(logicButton).toHaveText('AND');
  //   await expect(page.getByTestId('employee-list')).not.toContainText(/./);

  //   await logicButton.click();
  //   await expect(logicButton).toHaveText('OR');

  //   await expect(page.getByTestId('employee-list')).toContainText(/./);
  //   await page.getByLabel('Machines').evaluate((el:HTMLSelectElement) => (el.value = ''));

  //   if (await page.getByLabel('Employees').isVisible().catch(() => false)) {
  //     await page.getByLabel('Employees').selectOption({ label: 'Emily Rodriguez' });
  //     await page.getByLabel('Employees').selectOption({ label: 'Sarah Johnson' }); 
  //     await expect(logicButton).toHaveText('AND');
  //     await expect(page.getByTestId('machine-list')).not.toContainText(/./);
  //     await logicButton.click();
  //     await expect(logicButton).toHaveText('OR');
  //     await expect(page.getByTestId('machine-list')).toContainText(/./);
  //   }
  // });
});
