import { useState, useMemo } from 'react';

import { TopNav } from './components/TopNav';
import { Sidebar } from './components/Sidebar';
import { ResourceGrid } from './components/ResourceGrid';
import { AllocationPanel } from './components/AllocationPanel';
import { AdvancedFilters, AdvancedFilter } from './components/AdvancedFilters';
import { ResourceSetsView } from './components/ResourceSetsView';
import type { ResourceSet } from './components/ResourceSetTable';
import { AutoGeneratedSetsView } from './components/AutoGeneratedSetsView';
import { ResourceDrillDown } from './components/ResourceDrillDown';
import * as Tooltip from '@radix-ui/react-tooltip';
import { mockResources } from './components/mockResources';
import { Resource } from './Type';

import { useState as useReactState } from 'react';
import { FilterUtils } from './FilterUtils';

export default function App() {
  const [currentView, setCurrentView] = useState<'resources' | 'sets' | 'auto-sets'>('resources');
  const [selectedTypes, setSelectedTypes] = useState<string[]>(['all']);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedResourceIds, setSelectedResourceIds] = useState<string[]>([]);
  const [advancedFilters, setAdvancedFilters] = useState<AdvancedFilter[]>([]);
  const [resourceSets, setResourceSets] = useState<ResourceSet[]>([]);
  const [drillDownResource, setDrillDownResource] = useState<Resource | null>(null);
  const [isAdvancedFiltersOpen, setIsAdvancedFiltersOpen] = useReactState(false);

  const handleTypeToggle = (type: string) => {
    if (type === 'all') {
      setSelectedTypes(['all']);
    } else {
      setSelectedTypes([type]);
    }
  };

  const handleSelectResource = (id: string) => {
    setSelectedResourceIds(prev =>
      prev.includes(id) ? prev.filter(rid => rid !== id) : [...prev, id]
    );
  };

  const handleRemoveResource = (id: string) => {
    setSelectedResourceIds(prev => prev.filter(rid => rid !== id));
  };

  const handleClearAll = () => {
    setSelectedResourceIds([]);
  };

  const handleSaveSet = () => {
    if (selectedResourceIds.length === 0) return;
    
    const newSet: ResourceSet = {
      id: `set-${Date.now()}`,
      name: `Resource Set ${resourceSets.length + 1}`,
      resources: mockResources.filter(r => selectedResourceIds.includes(r.id)),
      createdAt: new Date()
    };
    
    setResourceSets(prev => [...prev, newSet]);
    setSelectedResourceIds([]);
    setCurrentView('sets');
  };

  const handleDeleteSet = (id: string) => {
    setResourceSets(prev => prev.filter(set => set.id !== id));
  };

  const handleEditSet = (id: string) => {
    const set = resourceSets.find(s => s.id === id);
    if (set) {
      setSelectedResourceIds(set.resources.map(r => r.id));
      setCurrentView('resources');
    }
  };

  // Advanced filtering logic now imported from filterUtils

  // ...existing code...

  const filteredResources = useMemo(() => {
    let filtered = mockResources;

    // Type filter
    filtered = filtered.filter(resource => {
      return selectedTypes.includes('all') || selectedTypes.includes(resource.type);
    });

    // Search filter
    filtered = filtered.filter(resource => {
      if (searchQuery === '') return true;
      const query = searchQuery.toLowerCase();
      return (
        resource.name.toLowerCase().includes(query) ||
        resource.department?.toLowerCase().includes(query) ||
        resource.location?.toLowerCase().includes(query) ||
        resource.skills?.some(skill => skill.toLowerCase().includes(query))
      );
    });

    // Advanced filters
    filtered = FilterUtils.applyAdvancedFilters(filtered, advancedFilters);

    return filtered;
  }, [selectedTypes, searchQuery, advancedFilters]);

  const selectedResources = useMemo(() => {
    return mockResources.filter(r => selectedResourceIds.includes(r.id));
  }, [selectedResourceIds]);

  const currentResourceType = selectedTypes.includes('all') ? 'all' : selectedTypes[0] || 'all';

  return (
    <Tooltip.Provider>
      <div className="h-screen flex flex-col bg-background">
        <TopNav currentView={currentView} onViewChange={setCurrentView} />
        
        <div className="flex-1 flex overflow-hidden">
          {currentView === 'resources' && (
            <>
              <Sidebar
                selectedTypes={selectedTypes}
                onTypeToggle={handleTypeToggle}
                searchQuery={searchQuery}
                onSearchChange={setSearchQuery}
                shrinkResourceType={isAdvancedFiltersOpen}
                advancedFilters={
                  <AdvancedFilters
                    resources={mockResources}
                    filters={advancedFilters}
                    onFiltersChange={setAdvancedFilters}
                    currentResourceType={currentResourceType}
                    isExpanded={isAdvancedFiltersOpen}
                    setIsExpanded={setIsAdvancedFiltersOpen}
                  />
                }
              />
              
              <main className="flex-1 overflow-y-auto p-8">
                <div className="max-w-7xl mx-auto">
                  <div className="mb-6">
                    <h1 className="text-[var(--navy)] mb-2">Available Resources</h1>
                    <p className="text-muted-foreground text-sm">
                      Select resources to build your allocation set
                      {filteredResources.length > 0 && (
                        <span className="ml-2">• Showing {filteredResources.length} resource{filteredResources.length !== 1 ? 's' : ''}</span>
                      )}
                    </p>
                  </div>
                  
                  <ResourceGrid
                    resources={filteredResources}
                    selectedResources={selectedResourceIds}
                    onSelectResource={handleSelectResource}
                    onDrillDown={setDrillDownResource}
                    allResources={mockResources}
                  />
                </div>
              </main>
              
              <AllocationPanel
                selectedResources={selectedResources}
                onRemoveResource={handleRemoveResource}
                onClearAll={handleClearAll}
                onSaveSet={handleSaveSet}
              />
            </>
          )}

          {currentView === 'auto-sets' && (
            <main className="flex-1 overflow-y-auto p-8">
              <div className="max-w-7xl mx-auto">
                <div className="mb-6">
                  <h1 className="text-[var(--navy)] mb-2">Auto-Generated Compatible Sets</h1>
                  <p className="text-muted-foreground text-sm">
                    Explore fully compatible resource sets automatically generated based on compatibility constraints
                  </p>
                </div>
                
                <AutoGeneratedSetsView
                  allResources={mockResources}
                  onSelectResource={handleSelectResource}
                  onAddSet={set => {
                    setResourceSets(prev => [
                      ...prev,
                      {
                        ...set,
                        id: `set-${Date.now()}`,
                        name: `Resource Set ${resourceSets.length + 1}`,
                        createdAt: new Date(),
                      },
                    ]);
                    setCurrentView('sets');
                  }}
                />
              </div>
            </main>
          )}

          {currentView === 'sets' && (
            <main className="flex-1 overflow-y-auto p-8">
              <div className="max-w-7xl mx-auto">
                <div className="mb-6">
                  <h1 className="text-[var(--navy)] mb-2">Saved Resource Sets</h1>
                  <p className="text-muted-foreground text-sm">
                    Manage your saved resource allocation sets
                    {resourceSets.length > 0 && (
                      <span className="ml-2">• {resourceSets.length} set{resourceSets.length !== 1 ? 's' : ''} saved</span>
                    )}
                  </p>
                </div>
                
                <ResourceSetsView
                  sets={resourceSets}
                  onDeleteSet={handleDeleteSet}
                  onEditSet={handleEditSet}
                />
              </div>
            </main>
          )}
        </div>

        {drillDownResource && (
          <ResourceDrillDown
            resource={drillDownResource}
            allResources={mockResources}
            onClose={() => setDrillDownResource(null)}
            onSelectResource={handleSelectResource}
          />
        )}
      </div>
    </Tooltip.Provider>
  );
}